name: Build & Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm test --coverage
        env:
          ETH_MAINNET_RPC: ${{ secrets.ETH_MAINNET_RPC }}
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
          flags: unittests
          verbose: true
